### ISSUE TITLE
ClassCastException in Http4sWebContext

### ISSUE THREAD

**Issue by mprevel** [pac4j/http4s-pac4j#25]
Hi,

I encounter an issue in the `Http4sWebContext` that rises a:

```
2023-08-08T22:15:14.025Z [io-compute-9] ERROR o.h.s.service-errors - Error servicing request: GET /protected/sample1 from 127.0.0.1  
java.lang.ClassCastException: class org.pac4j.http4s.Http4sWebContext$Pac4jUserProfiles cannot be cast to class java.util.Map (org.pac4j.http4s.Http4sWebContext$Pac4jUserProfiles is in unnamed module of loader sbt.internal.LayeredClassLoader @10341fed; java.util.Map is in module java.base of loader 'bootstrap')
        at org.pac4j.core.profile.ProfileManager.lambda$retrieveAll$0(ProfileManager.java:79)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.pac4j.core.profile.ProfileManager.retrieveAll(ProfileManager.java:77)
        at org.pac4j.core.profile.ProfileManager.getProfiles(ProfileManager.java:64)
        at org.pac4j.core.engine.DefaultSecurityLogic.loadProfiles(DefaultSecurityLogic.java:181)
        at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:130)
        at org.pac4j.http4s.SecurityFilterMiddleware$.securityFilter$$anonfun$1$$anonfun$1$$anonfun$1(SecurityFilterMiddleware.scala:87)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at liftF @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:191)
        at flatMap @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:203)
        at delay @ org.pac4j.http4s.Session$.debug(Session.scala:170)
        at liftF @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:191)
        at flatMap @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:203)
        at flatMap @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:203)
        at liftF @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:191)
        at map @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1$$anonfun$1(Session.scala:196)
        at flatMap @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:203)
        at delay @ org.pac4j.http4s.Session$.debug(Session.scala:170)
        at liftF @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:191)
        at flatMap @ org.pac4j.http4s.Session$.sessionManagement$$anonfun$1$$anonfun$1(Session.scala:203)
        at orElse @ org.http4s.server.Router$.define$$anonfun$2$$anonfun$1(Router.scala:82)
        at getOrElse @ org.http4s.syntax.KleisliResponseOps.orNotFound$$anonfun$1(KleisliSyntax.scala:47)
```

It seems to work as expected when I replace the inner case class `Http4sWebContext#Pac4jUserProfiles` with a type alias and remove its use at line 103, but I don't know if it has other impacts (tests are OK with these changes).

So the changes I did are :

```
type Pac4jUserProfiles = util.LinkedHashMap[String, CommonProfile]
```

and

```
request.withAttribute(pac4jUserProfilesAttr, value.asInstanceOf[util.LinkedHashMap[String, CommonProfile]])
```

It can be reproduced with a minimal client.

```
final case class SimpleCredentials() extends Credentials {
  override def getUserProfile: CommonProfile =
    val profile = new CommonProfile()
    profile.setId("my_id")
    profile.addAttribute(Pac4jConstants.USERNAME, "my_username")
    profile
}

final class SimpleCredentialsExtractor() extends CredentialsExtractor {
  override def extract(context: WebContext, sessionStore: SessionStore): ju.Optional[Credentials] =
    ju.Optional.of(SimpleCredentials())
}

final class SimpleClient() extends DirectClient {
  override protected def internalInit(forceReinit: Boolean): Unit =
    defaultCredentialsExtractor(SimpleCredentialsExtractor())
    defaultAuthenticator(
      new Authenticator {
        override def validate(credentials: Credentials, context: WebContext, sessionStore: SessionStore): Unit =
          println("credentials assumed valid")
      }
    )
}
```

Did I miss something?

Regards,

**Comment by leleuj** [comment]
I'm not sure. Can you submit a PR? Thx

**Comment by mprevel** [comment]
I've just created a PR and added some info about what I think could be the issue.

**Comment by leleuj** [comment]
Thanks for your help.
